### PR TITLE
R30 with costs and Yeast Gates models

### PR DESCRIPTION
**Pull request by ukuter**
Moving the R30 models with costs over to the new git dev branch. Latest Yeast Gates models which seemed to be working in general modulo a couple fixes necessary here and there.

### CODE REVIEW

**Comment by mwes** [comment]
Can one of the admins verify this patch?

**Comment by mdehavensift** [comment]
Retest this please.

**Comment by mdehavensift** [comment]
Test comment

**Comment by mdehavensift** [comment]
Test message

**Pull request merged**
