### PR TITLE
cleanup to make build smoother

### PR DESCRIPTION
**Pull request by danbryce**

### CODE REVIEW

**Comment by mwes** [comment]
Can one of the admins verify this patch?

**Comment by mwes** [comment]
ok to test

**Comment by mwes** [comment]
ok to test

**Comment by mwes** [comment]
retest this please

**Comment by danbryce** [comment]
retest this please

**Comment by danbryce** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
@danbryce The issue with the docker container already existing during the jenkins build is now fixed. The test is still failing though. This is because it is testing an early Q0 r30 problem which no longer works. I've updated the test to work on the Q1 r30 problem in #3. If you either merge that branch or rebase with it, the tests should pass for this branch.

**Pull request merged**
